name: Render formelsammlung.pdf
on: push

permissions:
  contents: write

jobs:
  render-fosa:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Get Previous tag
        id: previoustag
        uses: WyriHaximus/github-action-get-previous-tag@v2
      - name : Install fonts
        run: sudo apt-get update && sudo apt-get install fonts-texgyre fonts-texgyre-math
      - name: Setup Typst
        uses: typst-community/setup-typst@v5
      - name: Compile Document
        run: typst compile --input version=${{ steps.previoustag.outputs.tag }} --pdf-standard 2.0 --no-pdf-tags formelsammlung.typ
      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          name: "${{ github.ref_name }}"
          files: "*.pdf"
