name: Render formelsammlung.pdf
on: push

permissions:
  contents: write

jobs:
  render-fosa:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Fontist
        uses: fontist/setup-fontist@v2
      - name: Install fonts
        run: fontist install "TeX Gyre Pagella" #"TeX Gyre Pagella Math" "TeX Gyre Heros"
      - name: Setup Typst
        uses: typst-community/setup-typst@v5
      - name: Compile Document
        run: typst compile --pdf-standard 2.0 --no-pdf-tags formelsammlung.typ
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDFs
          path: |
            formelsammlung.pdf
      - name: Release
        uses: softprops/action-gh-release@v1
        if: github.ref_type == 'tag'
        with:
          name: "${{ github.ref_name }}"
          files: "*.pdf"
